### ISSUE TITLE
Chrome Autofill Form throws error

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#108]
In demo, if you type on the street input and chrome gives you suggestions based on the what was saved earlier, and if you select the one which will fill the street address, the city and the zip code, it throws an error and the application becomes non responding.

```
core.umd.js:3433 Error: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at ExpressionChangedAfterItHasBeenCheckedError.Error (native)
```

**Comment by mohammedzamakhan** [comment]
This error started from the last merge #107 

@aitboudad can you look into this please.

**Comment by aitboudad** [comment]
I'm on it see #109
