### ISSUE TITLE
Nested Property Keys

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#121]
INFO: http://angular-formly.com/#/example/advanced/nested-property-keys

**Comment by mohammedzamakhan** [comment]
@divyakumarjain @aitboudad Should we support this? since Angular 2 itself is not supporting it.

**Comment by divyakumarjain** [comment]
For scenarios where form layout is not nested but model does have nested properties it will be tricky to place nested fields across the form layout. But keeping these fields grouped at single location in layout is possible using formly groups.

i think is good to have but may not be must have.

**Comment by aitboudad** [comment]
I did some initial work and seems to be working fine, I'll provide a PR soon!

**Comment by mohammedzamakhan** [comment]
Thanks @Pouja 🎆 🌟 🎉

**Comment by FloNeu** [comment]
Ok. Hi, again guys - so this actually should be supported... But i am running into problems with this.
I got a nested model and want to refer to one of the keys from my FormlyfieldConfig, like: `key: "district.id"` with a model like`{ district: { id: 'UniqueId" }}` but when i set my model on the form the nested field value just isn't reflected (/gets deleted) on the model anymore.
