### ISSUE TITLE
[ts] Cannot find module 'ng2-formly'

### ISSUE THREAD

**Issue by bialad** [formly-js/ng2-formly#125]
I'm getting this error in vscode. Angular loads the module correctly, so it seems to only be a problem with types.

Looking into "node_modules/ng2-formly" there are no types, and trying to add "@types/ng2-formly" to package.json returns 404.

I'm a missing something here?

**Comment by aitboudad** [comment]
It should be fixed in the next release (#120)

**Comment by bialad** [comment]
I see.

Looking forward to it. :)

**Comment by mohammedzamakhan** [comment]
@bialad use 2.0.0-beta.7 version
