### ISSUE TITLE
Docs Generation

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#130]
I wanted to use typedoc [http://typedoc.org] for documentation generation, but it does not yet support for typescript 2.0.

**Comment by divyakumarjain** [comment]
Should we split this into two issue for easy tracking one for Document generation and second for Form Builder.

**Comment by aitboudad** [comment]
we should wait until the PR https://github.com/TypeStrong/typedoc/pull/290 is merged
