### ISSUE TITLE
Form Generator

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#135]
I wanted a Formly Generator, like what we had for angular 1 formly. 
example easyFormGenerator (https://github.com/MacKentoch/easyFormGenerator)

**Comment by mohammedzamakhan** [comment]
@joezhouOxford can you help us in creating form generator like you created for angular-formly?
http://www.spengineeringltd.com/Pages/FormBuilder.aspx#/FormDesign

We want to have this on ng2-formly website directly if possible.

**Comment by mohammedzamakhan** [comment]
https://github.com/formio/ngFormBuilder

This looks like a good form builder as well

**Comment by mohammedzamakhan** [comment]
@formly-js/angular2-formly-core-team

**Comment by thiagogjt** [comment]
https://github.com/formio/ng2-formio

**Comment by manushah** [comment]
Do we have any form generator/editor available ?

**Comment by aitboudad** [comment]
@manushah see https://github.com/franzeal/ng-formly-designer

**Comment by dlisovsky** [comment]
Hi @aitboudad @juristr do you know any other implementation of a form (formly) designer?
