### ISSUE TITLE
Handling onKeypress, onEnter, onLeave, onClick, onFocus, onBlur, onChange etc.

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#147]
Lets discuss how can we deal with this. Angular 1 formly had this to tackle it, but we don't have anything in place yet.

``` js
     {
        key: 'text1',
        type: 'input',
        templateOptions: {
          onKeypress: function($viewValue, $modelValue, scope) {
            console.log('The key was pressed!', $viewValue);
          }
        }
      }
```

**Comment by jrgleason** [comment]
Did that merge fix onChange? I don't see anything in the diff. I am trying a select with onChange right now and it isn't working

"ng2-formly": "^2.0.0-beta.13",

**Comment by paigudepooja** [comment]
@mohammedzamakhan  I want to call a function on click of particular key. How can I achieve that ?
