### ISSUE TITLE
Expression properties should be able to take function

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#148]
I tried function for expression properties, but I failed doing that, we need this feature for ng2-formly final.

``` ts
         expressionProperties: {
            'templateOptions.options': function() {
              if (this.model.title === 'mr') {
                return [{
                  label: 'Male',
                  value: 'male'
                }, {
                  label: 'Female',
                  value: 'female'
                }];
              } else {
                return [{
                  label: 'Female',
                  value: 'female'
                }, {
                  label: 'Male',
                  value: 'male'
                }];
              }
            }
          }
```

**Comment by Riron** [comment]
A similar `eval` as [this one](https://github.com/formly-js/ng2-formly/blob/80df91815a26c75d01230152eb98f08c8c052452/src/services/formly.field.delegates.ts#L7) would be nice - and nearly usable as is 😄

**Comment by lizarajesh** [comment]
How to disable an input using expressionProperties on a button click.?
If i given like this 
 "expressionProperties": {
          "templateOptions.disabled": "true"
        } it is working fine. But i would like to disable this on a button click.
It would great if u help me !!

**Comment by aitboudad** [comment]
@lizarajesh see https://ngx-formly.github.io/ngx-formly/examples/form-options/form-state
