### ISSUE TITLE
Merging validators and validation as well as asyncValidators and asyncValidation

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#170]
It would be better to have just validators and asyncValidator like in angular-formly

**Comment by aitboudad** [comment]
can you explain more on this ?

**Comment by mohammedzamakhan** [comment]
Instead of having validation: Validators.required, I can have validators: { validation: Validators.required}

Benefit: We now have validation property that can be used similar to angular-formly
http://docs.angular-formly.com/docs/field-configuration-object

We should always try to bridge the gap between angular 1 and 2 field configuration as much as possible

**Comment by mohammedzamakhan** [comment]
Closing this as #165 will take care of this
