### ISSUE TITLE
not bundle with webpack (lost control.service.d.ts)

### ISSUE THREAD

**Issue by aMoRRoMa** [formly-js/ng2-formly#18]
[default] /Users/roma/git/sos_manager_front/node_modules/ng2-formly/src/components/formly.form.d.ts (3,32):
    Cannot find module './../services/control.service'.
[default] /Users/roma/git/sos_manager_front/node_modules/ng2-formly/src/main.d.ts (4,32):
    Cannot find module './services/control.service'.
[default] /Users/roma/git/sos_manager_front/node_modules/ng2-formly/src/services/formly.providers.d.ts (1,32):
    Cannot find module './control.service'.

**Comment by brutalcrozt** [comment]
Hello @aMoRRoMa , thanks for your issue. Somehow i don't use angular 2 yet, maybe @mohammedzamakhan can give some clear point.

**Comment by divyakumarjain** [comment]
is this duplicate of #32
