### ISSUE TITLE
Add an event on form controls ready

### ISSUE THREAD

**Issue by Riron** [formly-js/ng2-formly#183]
In order to know when the form controls have been registered, it would be nice to have something like a `(controlsReady)` event. It would be emitted after [registerFormContols](https://github.com/formly-js/ng2-formly/blob/2b200b23421175c30febc2a03404b2baafd6986c/src/components/formly.form.ts#L44) has completed I guess.

This would enable us to observe controls valuesChanges safely.

**Comment by mohammedzamakhan** [comment]
@Riron nice idea, can you make a PR and update the demo with a nice example. Even I was not able to observe the controls, I had to observe the form and then observe the control if available.

**Comment by aitboudad** [comment]
Instead you can use `lifecycle` see https://github.com/formly-js/ng2-formly/pull/151
