### ISSUE TITLE
Repeat Section type support

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#189]
I tried having repeat section support to ng2-formly, similar to what we have in `angular-formly` (ng1), but was not able to get any solution, since the keys are same for those repeat section. 

ng1: http://jsbin.com/murule/32/edit
ng2: http://plnkr.co/edit/HmXMUyQ0NmB4eyZdX3bN?p=preview

What could be the best way to handle this?

@formly-js/angular2-formly-core-team

**Comment by thiagogjt** [comment]
@mohammedzamakhan 

Have you saw this example?
https://plnkr.co/edit/clTbNP7MHBbBbrUp20vr?p=preview

Source: https://scotch.io/tutorials/how-to-build-nested-model-driven-forms-in-angular-2
