### ISSUE TITLE
support for typeahead

### ISSUE THREAD

**Issue by fdu-axiometrics** [formly-js/ng2-formly#19]
Please take a look at this ng2 module for bootstrap 3/4. It has typeahead component you might be able to use.

http://valor-software.com/ng2-bootstrap/

This would be very helpful!

Thanks!

**Comment by mohammedzamakhan** [comment]
@fdu-axiometrics You can create a custom type of element, as shown in the example 

https://github.com/formly-js/ng2-formly/blob/master/demo/hello.ts#L99-L102
