### ISSUE TITLE
Radio buttons don't have names, so you can't use multiple groups

### ISSUE THREAD

**Issue by danielcrisp** [formly-js/ng2-formly#210]
If you have more than one group of radio buttons then they interfere with each other if the values are the same because the HTML element is not assigned a `name` attribute.

See this example (Title 1 and Title 2):

https://plnkr.co/edit/VejoJngnRhKhxcw5ZxxF?p=preview

The two sets of radio buttons have a different `key` so they should be independent, but if you change the selection you will see that it affects the other group.

I think using the `key` for the `name` attribute should fix it. I'll try it and submit a PR if it works

**Comment by danielcrisp** [comment]
Setting the `name` [doesn't help](https://github.com/danielcrisp/ng2-formly) - I think it might be something to do with the FormControl... investigating

**Comment by aitboudad** [comment]
I guess it's an angular issue, can you test the same example using `@angular/forms` only

**Comment by danielcrisp** [comment]
I've made a bit of progress (including fixing a similar problem with `multicheckbox`) but when I change the value of the field I see an array in the model, instead of the expected string.

See the demo in the [latest commit](https://github.com/danielcrisp/ng2-formly/tree/655b83a2bd833557dbb5b5194f55118cb0328297) 

Any ideas?

The first object is the model when the form is pristine. The second object is the model after changing `title1` and `title2`.

![image](https://cloud.githubusercontent.com/assets/1104814/19894348/9631d3ec-a044-11e6-916a-3cad58cccb61.png)

**Comment by aitboudad** [comment]
because you have defined the radio control as `FormArray` which is not correct
https://github.com/danielcrisp/ng2-formly/blob/655b83a2bd833557dbb5b5194f55118cb0328297/src/ui-bootstrap/types/radio.ts#L21

**Comment by danielcrisp** [comment]
Cool, think I've figured it out - I had to follow this: https://angular.io/docs/ts/latest/api/forms/index/RadioControlValueAccessor-directive.html but use the main `form` as the `formGroup` within the radio group

Take a look: https://github.com/formly-js/ng2-formly/pull/212
