### ISSUE TITLE
Layout broken with Bootstrap v4 flexbox support enabled

### ISSUE THREAD

**Issue by danielcrisp** [formly-js/ng2-formly#215]
I think its because of all the nested custom elements, e.g. `<formly-field>` etc

![image](https://cloud.githubusercontent.com/assets/1104814/19898892/d5552446-a055-11e6-810d-6aa22fec2f3b.png)

Try the demo with this as the CSS source:

https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap-flex.min.css

**Comment by danielcrisp** [comment]
This might help, but perhaps there is a better way of fixing this...

http://codepen.io/anon/pen/JRgBZX

Using `<template>` to output the components directly to the DOM without the additional elements?

**Comment by mohammedzamakhan** [comment]
If you use flexbox, the column class element should be direct child of row class element.
