### ISSUE TITLE
Differentiator with Ng2 Forms

### ISSUE THREAD

**Issue by benoror** [formly-js/ng2-formly#22]
I've been thinking what's the differentiator of using this lib instead of **Ng2 Form components & Form Builder**:

- https://angular.io/docs/ts/latest/guide/forms.html
- http://learnangular2.com/forms/#formbuilder

I put the issue on the table to see if some synergy can be done, maybe this can be re-used in some way, trying not to re-invent the wheel.

This might be related to: https://github.com/formly-js/ng2-formly/issues/21

**Comment by mohammedzamakhan** [comment]
@benoror if you look at formly, you get the benefit of not writing a line of html, where as if you would have used form builder, you would have had to write the html markup.

**Comment by Mig1st4ck** [comment]
Formly is cool if you want to build a form with basically only Json. its easy to create big forms and allow great control of the html emited because all the html its from the templates.

**Comment by benoror** [comment]
Fair enough, thanks for the feedback guys!
