### ISSUE TITLE
FormlyWrapperHorizontalLabel

### ISSUE THREAD

**Issue by web265p3** [formly-js/ng2-formly#220]
Regarding the Quickstart: 
FormlyFieldToggle and FormlyWrapperHorizontalLabel is imported to the declarations-section of NgModule, but is not imported in the file itself. So I get an error message. What do I have to do to get this to work? :)

**Comment by aitboudad** [comment]
just remove them

**Comment by aitboudad** [comment]
see the basic example https://plnkr.co/edit/2hVrQUQ4li5MKVtZgPY1?p=preview
and for an advanced demo look at https://github.com/formly-js/ng2-formly/tree/master/demo

**Comment by web265p3** [comment]
Okay, thanks. This fixed my first issue. However, after doing the quickstart I still get an error message: "GET http://localhost:3000/ng2-formly 404 (Not Found)" whenever I add the "FormlyModule.forRoot(), FormlyBootstrapModule" to the declarations array in my module. The live example seems to work, so this must be my bad somehow... :)

**Comment by web265p3** [comment]
For SystemJS-Users:
Add:
`'ng2-formly' :            'node_modules/ng2-formly/bundles/ng2-formly.umd.js',`

to systemjs.config.js. 
That fixes the issue.
