### ISSUE TITLE
Extra formly tags removal

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#225]
Analyze whether we can remove the extra component tags by any means.

**Before:**

<img width="434" alt="screen shot 2016-11-03 at 10 17 18 am" src="https://cloud.githubusercontent.com/assets/2327532/20027289/17b03a58-a2de-11e6-9c83-30a350bd62cb.png">

**After removal of tags:**

<img width="433" alt="screen shot 2016-11-03 at 10 17 43 am" src="https://cloud.githubusercontent.com/assets/2327532/20027291/25a0928e-a2de-11e6-8cb1-8cbe3257b20d.png">

**Comment by mohammedzamakhan** [comment]
@formly-js/angular2-formly-core-team Need suggestions to tackle this issue.

**Comment by divyakumarjain** [comment]
This is how Angular 2 recommends Components to be added to DOM. In Angular 1 we had a way but dont think there is a way in Angular 2.

Are we running into any issue because of this?

**Comment by mohammedzamakhan** [comment]
@divyakumarjain look at the date of investment field above in both before and after pic

**Comment by divyakumarjain** [comment]
Haven't tried earlier and also not sure how much rework is this but may be formly-field-input can be converted into a directive instead of Component?

**Comment by mohammedzamakhan** [comment]
I don't think we can convert this into a directive, since directive won't contain a template 😞
