### ISSUE TITLE
Model binding to a formly-field in FormlyForm will not work with a nested property

### ISSUE THREAD

**Issue by Krustie101** [formly-js/ng2-formly#230]
In the template of  FormlyForm the model of the formly-field is bound via the expression

`[model]="field.key?model[field.key]:model"`

If field.key is a nested property (i.e. contains dots), model[field.key] will not be evaluated properly. I think a custom pipe could be used to handle nested properties (applied to model and field.key as a parameter).

**Comment by aitboudad** [comment]
define custom method is enough, can you work on it ?

**Comment by Krustie101** [comment]
@aitboudad 
No problem, I will take it up.

**Comment by mohammedzamakhan** [comment]
Any updates on this @Krustie101 ?

**Comment by Krustie101** [comment]
@mohammedzamakhan 

See pull request #293
