### ISSUE TITLE
event async loading in a field select

### ISSUE THREAD

**Issue by jcga82** [formly-js/ng2-formly#255]
I'm submitting a
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**
 In angular 1 I use controller for event async loading in a field select...

**Expected behavior**
but in ng2-formly I don´t know do it.

**Minimal reproduction of the problem with instructions**
<!--
If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar.
-->

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->

**Please tell us about your environment:**
<!-- IDE: webstorm 2016.2, chrome 54.0, rest api from django-rest-->

* **Angular version:** 2.0.1
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Thanks!

**Comment by mohammedzamakhan** [comment]
We use lifecycle hooks, check https://github.com/formly-js/ng2-formly/blob/master/demo/hello.ts#L82

**Comment by jcga82** [comment]
Thanks, but I already saw it. I do not know how to pass this code to version 2:

```javascript
loadLocalidades($scope, Server, $log) {
    'ngInject';
    $scope.$watch('model.provincia',function(newValue, oldValue){
      if(newValue !== oldValue || $scope.options.templateOptions.options.length == 0){
        $scope.to.loading = Server.get('provincias/'+newValue, 'localidades').then(
          (res) => {
            $scope.options.templateOptions.options = res.data[0].localidades;
            var localidadSelected = $scope.model.localidad;
            if(localidadSelected !== ''){
              $scope.model[$scope.options.key] = localidadSelected;
            }
            return res;
          }
        );
      }
    });
  }
```

**Comment by mohammedzamakhan** [comment]
Check this demo https://plnkr.co/edit/KC9VNIFohIgXRLg0FMAZ?p=preview

and also look at this demo from Angular 2 member for example of typeahead with reactive forms.

**Comment by jcga82** [comment]
Thanks you, the plunker help me a lot

**Comment by ampsarfraz** [comment]
@jcga82  hi, how did you achieve this finally? I am also trying to find a way to do exactly the same thing? Can you please post a sample?

**Comment by jcga82** [comment]
hi, here I put my code:
´´´js
lifecycle: {
                    onInit: function() {
                        this.form.get('provincia').valueChanges.subscribe(
                            (id_provincia:any) => {
                                let dataLocalidades = localidadResource.get({id: id_provincia});
                                dataLocalidades
                                    .$observable
                                    .subscribe(
                                        (localidadesRecibidas) => {
                                            dataLocalidades = localidadesRecibidas[0].localidades;
                                            this.field.templateOptions.options = dataLocalidades;
                                        }
                                    );
                            }
                        );
                    },
                }
´´´

**Comment by ampsarfraz** [comment]
Thank you. Sorry to bother again. How did you pass localidadResource as a dependency injection to the component? 

When I try to pass my service I get an undefinederror.

**Comment by ampsarfraz** [comment]
@jcga82 Thank you. Sorry to bother again. How did you pass localidadResource as a dependency injection to the component?

When I try to pass my service I get an undefined error.

**Comment by jcga82** [comment]
First you import  your resource
```javascript
import {LocalidadResource, ILocalidad} from "../../resources/localidad.resource";
```
Then you add to the constructor as params
```javascript
private localidadResource:LocalidadResource
```
You have not to do nothing, all it do ng2-resource rest...
