### ISSUE TITLE
valueProp and labelProp in type select

### ISSUE THREAD

**Issue by jcga82** [formly-js/ng2-formly#258]
I'm submitting a:
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request
```

**Current behavior**
valueProp and labelProp not work. In ng-formly work fine.

**Expected behavior**
I need map a json for select and it has not value and label elements...

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Now I map it without native formly

**Please tell us about your environment:**

* **Angular version:** 2.0.1

* **Browser:** [all | Chrome X | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript 7.0 | ES6/7 | ES5]

**Comment by mohammedzamakhan** [comment]
@jcga82 Can you look into this and make a PR. Would be appreciated.

**Comment by jcga82** [comment]
I do not think I can but I'll try it.

**Comment by mohammedzamakhan** [comment]
You will have to make changes to this file https://github.com/formly-js/ng2-formly/blob/master/src/ui-bootstrap/types/select.ts
