### ISSUE TITLE
Expression properties error

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#270]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 

```

**Current behavior**
The field gets enabled but gives out error after that
**Expected behavior**
It should enable and disable propertly
**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/XYZ1N8Y3cFHKgZIejrIA?p=preview

**Comment by aitboudad** [comment]
We should execute expression delegate during form building

**Comment by mohammedzamakhan** [comment]
@aitboudad status?

**Comment by aitboudad** [comment]
I'll provide a PR tomorrow

**Comment by mohammedzamakhan** [comment]
This looks like issue in the plnkr now http://plnkr.co/edit/zFLjKwxVvNm1aSghMi6l?p=preview
