### ISSUE TITLE
Request for an example for options for select field from a remote API through a service

### ISSUE THREAD

**Issue by ampsarfraz** [formly-js/ng2-formly#271]
I'm submitting a support request.

The request is for an example to fetch options for a select field from a remote API through a service. 

Below is an option that I tried, however I couldn't get it to work.
I tried extending the FormlyFieldSelect but I am not able to inject a service into the constructor of the child class. The service always comes up as `undefined`.

```
import { NgModule, Component, OnInit} from '@angular/core';
import { EntityrecordApi } from '../sdk/services/custom';
import { Injectable, Inject } from '@angular/core';
import { FormlyFieldSelect } from 'ng2-formly';

@Component({
  selector: 'formly-field-lookup-select',
  providers: [EntityrecordApi],
  template:'<div>Test</div>'
})

export class LookupSelect extends FormlyFieldSelect implements OnInit{
  constructor(private _EntityrecordApi: EntityrecordApi) {
   super()
  }
  ngOnInit(): void {
   //Do Something here
    this._EntityrecordApi.find()
  }
}
```
![image](https://cloud.githubusercontent.com/assets/23452573/20471098/c00f0820-afd4-11e6-8026-bfc6d64538e9.png)

**Comment by mohammedzamakhan** [comment]
Can you make a simple plnkr so that we can make that work?

**Comment by jrgleason** [comment]
Related to https://github.com/formly-js/ng2-formly/issues/277 I believe

**Comment by mohammedzamakhan** [comment]
Could this pull request be of any help to you? https://github.com/formly-js/ng2-formly/pull/286
