### ISSUE TITLE
Field with nested property loses wrappers

### ISSUE THREAD

**Issue by franzeal** [formly-js/ng2-formly#282]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
When a field's key uses nested properties, the field's type wrappers get lost.

**Expected behavior**
When a field's key uses nested properties, the field's type wrappers should remain.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/hJPG6QFfMDAYja9WSBd7?p=preview

**Comment by aitboudad** [comment]
see #284
