### ISSUE TITLE
Not getting Typescript and Webpack config when using github and npm

### ISSUE THREAD

**Issue by jrgleason** [formly-js/ng2-formly#308]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**

1. Add `"ng2-formly": "git://github.com/formly-js/ng2-formly.git"` to package.json
2. Go into node_modules/ng2-formly 
3. Run `npm install`
4. Notice it complains about the Typescript config.

**Workaround**

Copy files from a typical clone of the git repo

**Expected behavior**
I should get a valid build without work around

I tried this on OSX and Windows.

**Comment by jrgleason** [comment]
Looks like this is the culprit....

https://github.com/formly-js/ng2-formly/blob/master/.npmignore

**Comment by mohammedzamakhan** [comment]
Please create a PR for the change 😄

**Comment by jrgleason** [comment]
Will do, are we sure we want to allow these files to be downloaded over npm? Do we just need the build typescript config or the regular one as well? What Webpack configs should be included? All?

**Comment by jrgleason** [comment]
There is your pull request... It seems cheap to become a contributing coder on something this menial.

**Comment by mohammedzamakhan** [comment]
@jrgleason yayyy!!! Thanks 👍

**Comment by jrgleason** [comment]
Still some issues unfortunately. I tried to only add a couple files and I was assuming some things would happen. This was not the case, however, I am curious why spec files are being used if we are not supposed to be callings tests when running build. 

So the real question is, why would I get...

```
ERROR in [at-loader] src/core/utils.spec.ts:5:3 
    Cannot find name 'describe'.
```

When running npm run build? shouldn't I need to run npm run test?

**Comment by mohammedzamakhan** [comment]
Make sure that you make changes to your repo and make changes to it and instead of 

```js
"ng2-formly": "git://github.com/formly-js/ng2-formly.git"
```

use 

```js
"ng2-formly": "git://github.com/jrgleason/ng2-formly.git"
```

and test it out in your next PR 😄
