### ISSUE TITLE
How can i implement repeating section using ng2-formly

### ISSUE THREAD

**Issue by parimal-padture** [formly-js/ng2-formly#312]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

**Expected behavior**

As in anguar-formly we are allowed to add custom template which can be used to implement repeating section , so how can i implement that feature using ng2-formly
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

windows 7, chrome, visual studio code, node.js
* **Angular version:** 2.0.X

angular 2.2.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10 ES5
* **Node (for AoT issues):** `node --version` =   7.2.1

**Comment by mohammedzamakhan** [comment]
Checkout our introductory example, which has an example of repeated section 

https://ng2.angular-formly.com/guides/introductory-example.html

**Comment by parimal-padture** [comment]
Thanks that helped a lot.
