### ISSUE TITLE
how can I possibly use ng2-translate with ng2-formly - fields-label?

### ISSUE THREAD

**Issue by itcozum** [formly-js/ng2-formly#313]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mohammedzamakhan** [comment]
http://plnkr.co/edit/IGB100i4VeouQzANShZJ?p=preview

**Comment by jogelin** [comment]
@mohammedzamakhan How do you use translation within the config file ?

For example, I would like to inject translation for the global validation messages:
```
....
  validationMessages: [
    { name: 'required', message: requiredValidationMessage },
    { name: 'invalidEmailAddress', message: 'Invalid Email Address' },
    { name: 'maxlength', message: 'Maximum Length Exceeded.' },
    { name: 'minlength', message: minlengthValidationMessage },
    { name: 'not_matching', message: 'Password Not Matching' },
    { name: 'zipCode', message: 'ZIP code should be 5 characters'},
    { name: 'uniqueUsername', message: 'This username is already taken.'},
  ],
.......
```

Is it possible ?

For the moment, I just created an angular service that inject common validationMessages for each formConfig...

**Comment by aitboudad** [comment]
@jogelin in that case you have to use [FormlyConfig](https://github.com/formly-js/ng-formly/blob/master/src/core/src/services/formly.config.ts) service by calling `addValidatorMessage` when translations is loaded

**Comment by witek1902** [comment]
Example from our repo:
https://github.com/asc-lab/ngx-formly-playground/blob/master/app-formly-playground/src/app/shared/services/validations.loader.ts
