### ISSUE TITLE
FieldExpression does not applied to field with FieldGroup

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ng2-formly#317]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Comment by mohammedzamakhan** [comment]
@aitboudad I still see that it doesn't work

http://plnkr.co/edit/zFLjKwxVvNm1aSghMi6l?p=preview

**Comment by aitboudad** [comment]
I try to reproduce it in the demo app without success, could you check on your pc ?

**Comment by mohammedzamakhan** [comment]
Even I can't reproduce it on my machine, its probably just the plnkr?

**Comment by mohammedzamakhan** [comment]
Commented in the wrong issue
