### ISSUE TITLE
[Validation] Hidden fields should be marked as valid

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ng2-formly#318]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Comment by aitboudad** [comment]
The easy way is to attach/detach the `formControl` using `removeControl` and `addControl`

**Comment by aitboudad** [comment]
if should be done in [toggleHide](https://github.com/formly-js/ng2-formly/blob/master/src/core/components/formly.field.ts#L206) something like

```ts
if (this.field.formControl) {
  if (...) {
    this.form.removeControl(this.field.key);
  } else if (..) {
    this.form.addControl(this.field.key, this.field.formControl);
  }
}
```
 I leave for someone who want to contribute :)

**Comment by mohammedzamakhan** [comment]
@aitboudad lets do this ourselves and graduate the library to RC asap.

**Comment by aitboudad** [comment]
see #340
