### ISSUE TITLE
error TS2307: Cannot find module './control.service'.

### ISSUE THREAD

**Issue by fdu-axiometrics** [formly-js/ng2-formly#32]
Just installed with npm and added to my project. Got following errors when start my app.   

BTW, I am using webpack not systemjs

ERROR in C:\Users\fdu\Documents\Training\sing\angular2-seed\node_modules\ng2-formly\src\services\formly.providers.d.ts
    (1,32): error TS2307: Cannot find module './control.service'.

    ERROR in C:\Users\fdu\Documents\Training\sing\angular2-seed\node_modules\ng2-formly\src\components\formly.form.d.ts
    (3,32): error TS2307: Cannot find module './../services/control.service'.

    ERROR in C:\Users\fdu\Documents\Training\sing\angular2-seed\node_modules\ng2-formly\src\main.d.ts
    (4,32): error TS2307: Cannot find module './services/control.service'.

**Comment by MathijsHoogland** [comment]
What Angular version are you using?

**Comment by fdu-axiometrics** [comment]
beta15

**Comment by erynnb** [comment]
I think the npm package is missing the control.service.ts file. I was getting this error as well, then just copied the [control.service.ts file](https://github.com/formly-js/ng2-formly/blob/master/src/services/control.service.ts) into the ./services folder and it went away.
