### ISSUE TITLE
[BC][field-config] angular-formly use `wrapper` rather than `wrappers`

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ng2-formly#321]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
https://github.com/formly-js/ng2-formly/blob/master/src/core/components/formly.field.config.ts#L12

**Expected behavior**

http://docs.angular-formly.com/docs/field-configuration-object#wrapper-string--array-of-strings

I think we can keep `wrappers` and add wrapper as an alias and mark it as deprecated

**Comment by ColinRTaylor** [comment]
@aitboudad is the fix to just change `wrappers` to `wrapper` ? How can I add this as an alias?

**Comment by aitboudad** [comment]
I meant something like:

```
if (field.wrapper) {
   console.warn(`wrapper is deprecated. Use 'wrappers' instead.`);
   field.wrappers = field.wrapper;
}
```

can you work on it ?

**Comment by ColinRTaylor** [comment]
@aitboudad Yes, I'm going to give it a try and will submit a PR today, thank you very much!

**Comment by franzeal** [comment]
In the interest of backwards compatibility, could we also do something to handle when only a single wrapper was defined in angular-formly:

```
if (field.wrapper) {
   console.warn(`wrapper is deprecated. Use 'wrappers' instead.`);
   field.wrappers = Array.isArray(field.wrapper) ? field.wrapper : [field.wrapper];
}
```

**Comment by mohammedzamakhan** [comment]
@ColinRTaylor any update?

**Comment by ColinRTaylor** [comment]
@mohammedzamakhan @aitboudad 
I'm sorry but this is over my head. I tried over the weekend but couldn't get the tests to pass. Thanks for the opportunity though.
