### ISSUE TITLE
ng2-select with formly

### ISSUE THREAD

**Issue by ampsarfraz** [formly-js/ng2-formly#332]
**I'm submitting a support request 

**Current behavior**
I am trying to use ng2-select (https://github.com/valor-software/ng2-select) with formly primarily to use the Multiple select functionality.  I have created a custom type , but I am not able to get the selected value to be set in the form data. I have created a plunker for this. Can you please help me resolve this?

https://plnkr.co/edit/9p66odHMKDWh7BtwaAUM?p=preview

Thank you !

**Comment by mohammedzamakhan** [comment]
@ampsarfraz I hope this will be helpful https://plnkr.co/edit/j4A9AZ2B0BboSmUAyM7u?p=preview
