### ISSUE TITLE
Arrays in Property Keys

### ISSUE THREAD

**Issue by franzeal** [formly-js/ng2-formly#333]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
When a field's key contains an array indexer, formly does not treat that part of the key as an array.

**Expected behavior**
When a field's key contains an array indexer, formly should treat that part of the key as an array.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/AnIVMgao1dvjHsSkTDHh?p=preview

**What is the motivation / use case for changing the behavior?**
I have an existing angular-formly form that uses this capability that I'm porting.

**Comment by mohammedzamakhan** [comment]
For now you can do this like https://plnkr.co/edit/XhsLoifpOR29Wyr0uY0V?p=preview

**Comment by franzeal** [comment]
Sorry, I know I've seen that suggested before.  Workaround works fine, much appreciated!

**Comment by mohammedzamakhan** [comment]
@Krustie101 is expert in solving this issue 😅 

#293 PR had a solution to similar problem, but applied to different scenario.
