### ISSUE TITLE
Validators Expression not triggered for Checkboxes

### ISSUE THREAD

**Issue by Krisa** [formly-js/ng2-formly#337]
**I'm submitting a Bug**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
```
    {
        key: 'checked',
        type: 'checkbox',
        templateOptions: {
          label: 'Check me out',
          description: 'If you want to check me out, check this box',
        },
         validators: {
            required: {
               message: 'Click the checkbox',
               expression: (control: FormControl) => {  //NOT TRIGGERED  }
            }
         }
      }
```

**Expected behavior**
Clicking a checkbox shall trigger the expression, like it does for regular input text. I'm well aware that typing on a keyboard is different than clicking on a mouse. However is it something which could be supported? 

My use case is that I'm building a form dynamically (in the sense that I'm not aware of the fields) and I'm validating the form based on remote loaded config. Among others some checkboxes may need to be validated to make the form valid.

**Comment by mohammedzamakhan** [comment]
I see that its supported. Please post the plnkr with the issue

**Comment by Krisa** [comment]
My bad sorry for this, in my project I had `input` instead of `checkbox` for the attribute `type` and I put `checkbox` in templateOptions, much like a normal input text... (the example above taken from the demo app is actually fine). 

Now it works well, thank you for the quick feedback.
