### ISSUE TITLE
repeatSection / fieldArray does not emit form valueChanges

### ISSUE THREAD

**Issue by franzeal** [formly-js/ng2-formly#344]
```
[x] bug report
[ ] feature request
[x] support request
```

**Current behavior**
When a form's fields contains a type that uses a fieldArray, valueChanges are not emitted to the form.

**Expected behavior**
When a form's fields contains a type that uses a fieldArray, valueChanges should be emitted to the form.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/SGBo5LZhv0tPOKu4dKuU?p=preview

**What is the motivation / use case for changing the behavior?**
In this particular case, subscribing to the root FormGroup is being used as a means to support a debounced auto-save function.

**Comment by aitboudad** [comment]
see #345
