### ISSUE TITLE
resetModel broken with FormArrays

### ISSUE THREAD

**Issue by franzeal** [formly-js/ng2-formly#350]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
The ability to reset the model via options.resetModel is broken.  I've found that it has been broken starting with #329.  The following plunker uses that build of formly:
https://plnkr.co/edit/tK3LXcpGRwL3NM8rSb39?p=preview

**Expected behavior**
The following plunker uses the build of formly at #327, one commit prior with the expected behavior:
https://plnkr.co/edit/t5WgjlhyQiKxf6GfcGtY?p=preview

It's also worth looking at the behavior of the formly demo between these two commits as there are apparent problems with the repeatSection right off the bat which shouldn't have anything to do with the options.resetModel.

With the demo for the current build, an issue (possibly not the same) can be seen by just attempting to "Reset Model (New Model)" which should demonstrate the repeatSection not reflecting what's in the model.

**Comment by aitboudad** [comment]
If you remove the `json` pipe for `fields` property you'll see that both example work as expected.

**Comment by aitboudad** [comment]
Using the `json` pipe for `fields` property is not allowed anymore which can produce `Converting circular structure to JSON` as it contains `FormControl` instance

**Comment by mohammedzamakhan** [comment]
@aitboudad I closed #349 thinking its related to this issue

**Comment by aitboudad** [comment]
I'll look into it

**Comment by mohammedzamakhan** [comment]
I think we should go for Release Candidate once this bug is closed. Will have to rename the project to `ng-formly` and have to change it to `1.0.0-rc.0` and also probably change the url for the website from `ng2` to `ng`

**Comment by franzeal** [comment]
I've updated the plunker.  The broken example does not work as expected when commenting out the json pipe for fields.  Please observe what's in the model versus what's in the form.

**Comment by aitboudad** [comment]
@franzeal see https://plnkr.co/edit/PffGnzwxaYi0jvCsfZiZ?p=preview

```ts
  get fields(): FormlyFieldConfig[] {
    return JSON.parse(JSON.stringify(this.field.fieldArray.fieldGroup));
  }
```

**Comment by franzeal** [comment]
Try this:
https://plnkr.co/edit/HCc1ulSuOrOmNbLIn1v0?p=preview

**Comment by aitboudad** [comment]
@franzeal I had move the `fields` into getter see https://plnkr.co/edit/XxRDEXIYmJ3iMzGzQaXb
is it ok for you ?

**Comment by aitboudad** [comment]
see #353

**Comment by franzeal** [comment]
The plunker you just linked (https://plnkr.co/edit/XxRDEXIYmJ3iMzGzQaXb) is using the wrong build of formly (note the description at the top) and replace the formly.js contents with the latest build.

**Comment by aitboudad** [comment]
updated to the latest build see https://plnkr.co/edit/LkD7eReEFUsXakuMdqsQ?p=preview !

**Comment by franzeal** [comment]
Can you edit items in the repeatSection in the plunker?  I'm unable to.

**Comment by aitboudad** [comment]
fixed the issue of edit item, can you try again https://plnkr.co/edit/5rBWM4kjLKbRY80nLPcQ?p=preview

**Comment by franzeal** [comment]
@aitboudad that seems to have done it, awesome work!  I really appreciate your effort, especially that you've taken time out of your weekend to look at this.
