### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by fdu-axiometrics** [formly-js/ng2-formly#39]
I got following error when trying to use ng2-formly.

ng2-formly.js:1Uncaught ReferenceError: System is not defined

I'm using angular rc1 with webpack.
from this seed project https://github.com/AngularClass/angular2-webpack-starter

**Comment by fdu-axiometrics** [comment]
anyone got an idea for this?

We are in need of this library, but this thing really prevented us from using it.

**Comment by divyakumarjain** [comment]
Should we move away from typescript compiling to systemjs module. May be we can compile typescript to commonjs which is supported by both systemjs and webppack.
