### ISSUE TITLE
Two way Data Binding

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#45]
@divyakumarjain Can we look into this, I think this got broke after the control group logic was removed or something.

https://github.com/formly-js/ng2-formly/commit/09f97781f20f7527975eb37879509ed2216cf9b8#diff-69a89068190b42d36203ed92bed384f7L41

**Comment by divyakumarjain** [comment]
@mohammedzamakhan Can you please provide more detail about the issue so that we can reproduce the issue and fix it.

**Comment by divyakumarjain** [comment]
I think you are referring to Change Email Button functionality.

**Comment by mohammedzamakhan** [comment]
@divyakumarjain Yes 👍

**Comment by divyakumarjain** [comment]
As part of changeEmitter.subscribe the control group was getting created everytime there was a change thus external changes where picked up template directives.

https://github.com/formly-js/ng2-formly/pull/38/commits/09f97781f20f7527975eb37879509ed2216cf9b8#diff-69a89068190b42d36203ed92bed384f7L50

I dont thinking creating Control Group everytime will be best solution. Looking various blogs and post on internet related to Angular2 ngModel and ngControl to understand how this can be implemented.

**Comment by divyakumarjain** [comment]
Did lot of reading around change detection in Angular following are some helpful link related to this issue.

http://stackoverflow.com/questions/34635269/how-to-pass-input-params-to-an-angular-2-component-created-with-dynamiccompon
http://stackoverflow.com/a/34855772

So far theoretically there seems to be two possible way to solve this.
1. ngModel with ValueAccessor: Here writeValue method can be used to get updated value in template directive.
2. formly.field can have model as observable and template directive is subscribe to this.

observable option is more low level compared to ngModel option. Also ngModel may run into same problem of input bindings of Dynamic Component. Also ngModel option will need ValueAccessor Provider for individual template directive unless this accessor provider is implemented as generic service.

**Comment by divyakumarjain** [comment]
Following plnkr url showcases problem with two way binding for dynamically created directive

http://plnkr.co/edit/MBYdMP?p=preview

**Comment by mohammedzamakhan** [comment]
@divyakumarjain Is their any recommendations from Angular Team, if not is their a existing issue created about this in Angular repo?!

**Comment by divyakumarjain** [comment]
Few Post on Stacktrace talk about using observable on parent which is monitored by dynamic child. Parent should emit event on observable with right key else all the dynamic child will get the event. For this we need to look at ngOnChange at parent. But ngOnChange will not work with ngDoCheck as per angular documentation. Also if doe not work with complex objects.

Also i have raised below issue on Angular site.
https://github.com/angular/angular/issues/8903
