### ISSUE TITLE
Version 2.0.0-beta.3 typings error at installation

### ISSUE THREAD

**Issue by matthieubouvierthales** [formly-js/ng2-formly#48]
Here are the error messages : 

```
$ npm install ng2-formly

> ng2-formly@2.0.0-beta.3 postinstall /***/node_modules/ng2-formly
> typings install


sh: 1: typings: not found
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "ng2-formly"
npm ERR! node v4.4.2
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ng2-formly@2.0.0-beta.3 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
**npm ERR! Failed at the ng2-formly@2.0.0-beta.3 postinstall script 'typings install'.**
npm ERR! This is most likely a problem with the ng2-formly package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ng2-formly
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /***/npm-debug.log
```

There is a possibility to install typings globaly (is it a workaround or a new step in ng2-formly installation?):

```
$ npm install
npm WARN package.json ***@1.0.0 No license field.
/
> ng2-formly@2.0.0-beta.3 postinstall /***/node_modules/ng2-formly
> typings install

**typings WARN enoent Path "/***/node_modules/ng2-formly/typings.json" is missing**

└── (No dependencies)

ng2-formly@2.0.0-beta.3 node_modules/ng2-formly
└── reflect-metadata@0.1.2_


_$ ls -l node_modules/ng2-formly/
total 40
drwxrwxr-x 4096 mai   26 09:45 bundles
-rw-rw-r-- 1096 mai   11 23:21 LICENSE
-rw-rw-r-- 1 623 mai   20 19:10 ng2-formly.js
drwxrwxr-x 3 4096 mai   26 09:45 node_modules
-rw-rw-r-- 1 4530 mai   26 09:45 package.json
-rw-rw-r-- 1 4521 mai   11 23:21 README.md
drwxrwxr-x 5 4096 mai   26 09:45 src
-rw-rw-r-- 1 330 mai   26 05:39 tsconfig.build.json
```

But the ng2-formly.d.ts file is still missing and the project using ng2-formly is not compiling.

**Comment by dschoeni** [comment]
Worked good for me.

```                                                                                                   
> ng2-formly@2.0.0-beta.3 postinstall PATH\node_modules\ng2-formly      
> typings install                                                                                                                                                                              
                                                                                                          
ng2-formly@2.0.0-beta.3 node_modules\ng2-formly                                                           
├── reflect-metadata@0.1.2                                                                                
└── es6-shim@0.35.0                                                                                       
```

Also importing and building using webpack worked like a breeze with beta3.

**Comment by mohammedzamakhan** [comment]
@micouz Can you take a look into this

**Comment by micouz** [comment]
Sorry guys, a couple of things went wrong. I believe it should be fixed with this new PR.

**Comment by micouz** [comment]
@mohammedzamakhan Could you publish a new version ? Latest is still beta.3

**Comment by mohammedzamakhan** [comment]
@micouz Done

**Comment by dschoeni** [comment]
This hasn't worked as it should've guys:

After installing the module, there is more or less everything important missing. I can check out the repo, build it and use it with relative paths, but not with npm.

```
node_modules\ng2-formly
λ ls -l
total 24
-rw-r--r-- 1 usr 197609  1096 May 28 18:10 LICENSE
-rw-r--r-- 1 usr 197609  4521 May 28 18:10 README.md
drwxr-xr-x 1 usr 197609     0 May 28 18:10 node_modules/
-rw-r--r-- 1 usr 197609 10013 May 28 18:10 package.json
```

**Comment by micouz** [comment]
@dschoeni can you make sure you got the beta.4 version ?

Here's what I got:
```
➜  ng2-formly ls -l
total 28
drwxr-xr-x 2 mikael mikael 4096 mai   29 13:32 bundles
drwxr-xr-x 5 mikael mikael 4096 mai   29 13:32 lib
-rw-r--r-- 1 mikael mikael 1096 mai   11 23:21 LICENSE
-rw-r--r-- 1 mikael mikael 5066 mai   29 13:32 package.json
-rw-r--r-- 1 mikael mikael 4521 mai   11 23:21 README.md
```

**Comment by dschoeni** [comment]
No idea what happened, but another clean & reinstall using npm fixed it. I had the beta.4 version specified in my package.json. Welp, NPM caching goodness I guess.

Thanks for the great work and your quick response!

**Comment by mohammedzamakhan** [comment]
@micouz how do you import components? Through systemjs, I have to do, for it to work
``
import {FormlyConfig, TemplateDirectives, FormlyForm, FormlyEventEmitter} from 'index';
```

Shouldn't that be 

```
import {FormlyConfig, TemplateDirectives, FormlyForm, FormlyEventEmitter} from 'ng2-formly/index';
```

Example Plnkr http://plnkr.co/edit/yMuYFdBbfhAmB0HTROBk?p=preview

**Comment by matthieubouvierthales** [comment]
I have 2 problems with transpilation:

- I think the ng2-formly.d.ts file (and all .d.ts files) has to be in ng2-formly directory and not in ng2-formly/bundles.
- After copying ng2-formly.d.ts file and using `"import { FormlyProviders } from 'ng2-formly/ng2-formly';"`, I got the error: 
```
[gulp-tslint] error app/app.component.ts[14, 10]: unused variable: 'FormlyProviders'
sources/app/app.component.ts(14,33): error TS2306: File '/***/node_modules/ng2-formly/ng2-formly.d.ts' is not a module.
```

**Comment by micouz** [comment]
@mohammedzamakhan I'm not very good with System.js (I'm more a WebPack user), but I think some things are missing from your config.js file. Something like:
` map: {
    'ng2-formly': 'https://cdnjs.cloudflare.com/ajax/libs/ng2-formly/2.0.0-beta.4'
  },`
and:
`  packages: {
    'ng2-formly': {
      main: 'ng2-formly.js',
      defaultExtension: 'js'
    }
  }`

**Comment by micouz** [comment]
@matthieubouvierthales The bundles folder is used for CDN publication. In other cases, you will import the code from the lib folder.
When importing from the project, you should use:
`import { FormlyProviders } from 'ng2-formly`

**Comment by matthieubouvierthales** [comment]
@micouz You're right, we have to import with `import { FormlyProviders } from 'ng2-formly'` and not with `import { FormlyProviders } from 'ng2-formly/ng2-formly' ` like documented ont the [main page](https://github.com/formly-js/ng2-formly#quick-start).

Thanks for your work and your response !

**Comment by micouz** [comment]
@matthieubouvierthales Yes you're right, we changed the build system but not the documentation yet. I'm putting it on my todo list !
