### ISSUE TITLE
Can we add divyakumarjain to angular2 formly core team member?

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#51]
@kentcdodds please add @divyakumarjain to the angular 2 formly core team.

Thanks

**Comment by kentcdodds** [comment]
Done

**Comment by mohammedzamakhan** [comment]
Thanks a lot @kentcdodds 

Welcome @divyakumarjain as a new FormlyJS member. We appreciate your contributions to this repo. You have made invaluable contributions.
