### ISSUE TITLE
OPINION

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng2-formly#52]
I think we should rename our publishing to npm like how angular team did it.

Instead of importing like 

```
import {} from "ng2-formly/ng2-formly"; 

or 

import{} from "ng2-formly/core"
```

to 

```
import {} from "@formly/core"; 

or 

import{} from "@formly/templates"
```

Any other opinions/comments/suggestions

@divyakumarjain @micouz @TheMcMurder @MathijsHoogland

**Comment by TheMcMurder** [comment]
I actually like this idea. I think we're going to see a lot of angular specific libraries follow this convention.

**Comment by micouz** [comment]
Nice ! :+1: 
However, just to stay on the safe side, maybe we could ask someone close to or in the angular team if it is a good idea ?

**Comment by mohammedzamakhan** [comment]
@pkozlowski-opensource @johnpapa @gdi2290 @robwormald

Can you guys help us in this decision.

Thanks in advance 😄

**Comment by gdi2290** [comment]
`import {} from 'ng2-formly';`

**Comment by mohammedzamakhan** [comment]
@gdi2290 I saw even material2 started using @ 

```
import { MD_CARD_DIRECTIVES } from '@angular2-material/card';
```

Just wondering if the angular team is going to get rid of @ in the future releases or whats the reason you don't want formly to use @.

Thanks 👍

**Comment by gdi2290** [comment]
yeah I think you're looking for something like
`@formly/ng2`
  | `@formly/directives`
  | `@formly/templates `
  | `@formly/core`
where `@formly/core` is used both in other frameworks. If you don't plan on supporting other frameworks then `@formly/core` works as the default path for ng2.

**Comment by gdi2290** [comment]
I want this to be able to render on the server/webworker so it would also be great if you separated the platform logic and interacted with the renderer directly

**Comment by mohammedzamakhan** [comment]
@gdi2290 Thats in our pipeline :) ( #53 ) 

Thanks for your suggestion

**Comment by robwormald** [comment]
i wouldn't do this just for the sake of it, unless you really have a need to break out into smaller packages that are functionally independent - it's a non-trivial amount of work managing the process.

It makes sense for things like @ngrx or @material because they have a number of independently functional components or services, that can be independently distributed.

I'm not saying *don't*, just... consider if you really need to do this.

**Comment by mohammedzamakhan** [comment]
@robwormald 

I think it makes sense for our repo to have separate functional components, since we want to have templates are separate, and again the templates could be of bootstrap, ionic, material2 or any other.

Thanks a lot

**Comment by mohammedzamakhan** [comment]
To publish with @, npm will require us to make an organization which is paid on npm, so I think we should think about something else instead 😭

**Comment by mohammedzamakhan** [comment]
I am thinking about 

import {} from "formly"; 

or 

import{} from "formly-bootstrap"

or

import {} from "formly-ionic"

or 

or import {} from "formly-material"

**Comment by TheMcMurder** [comment]
I would prefer something like

````
import {} from 'formly/templates/bootstrap'
````
all templates could go in the 'template/${frameworkName}' directory for each css framework that is supported. 

I'm still pretty new to publishing things on NPM but couldn't we follow the same structure you had planned without the `@`?
