### ISSUE TITLE
Support Angular Universal

### ISSUE THREAD

**Issue by divyakumarjain** [formly-js/ng2-formly#53]
https://github.com/angular/universal

I am dont think Support for Angular Universal is a priority. But I was playing formly with Universal and debugging the issues.

Seems like there are few do's and don't 

1.  Should not use this.elem.nativeElement

Will document those do's and don'ts for now. So that later support for angular universal would be easy.

Let me know what everybody thinks. We can start maintaining markup file for this.

**Comment by gdi2290** [comment]
use the renderer when interacting with this.elem.nativeElement and you should be fine

**Comment by divyakumarjain** [comment]
@gdi2290 Thanks for you input. I think these input would be valuable. Are you referring to following class?

https://angular.io/docs/ts/latest/api/core/Renderer-class.html

are there any samples to look at to understand this class better.

**Comment by mohammedzamakhan** [comment]
I have used it to add event listeners on the window sometimes, like you can see it in primeng repo

https://github.com/primefaces/primeng/blob/587510d21af456f48c1069a7b01860564fce164c/components/menu/menu.ts
