### ISSUE TITLE
extend and multiple inheritance

### ISSUE THREAD

**Issue by cudasteve** [formly-js/ng2-formly#56]
I'm not sure what the appetite for major refactoring is on this rewrite, but one thing that was a little non-optimal in the original formly was the single-inheritance model used in the "extend" functionality.  Is there any interest in supporting more of a mixin-style to extending functionality of types, wrappers, manipulators, etc?

For example, in my ng1-formly project, I have a `base` type that contains functionality that I'd like to include in most (but not all) of my types.  I'd really love to have multiple different base types that include different things and then use some or all of them on each "downstream" type.

That said, I know multiple inheritance is a lot more complex than single inheritance.  And like I said, I'm not sure if you guys are trying to optimize things while rewriting or just doing a straight one-for-one rewrite.

**Comment by mohammedzamakhan** [comment]
This is not Formly for Angular 1.x, this is Formly for Angular 2.x version. This is not a rewrite of angular-formly in any way or form.

**Comment by cudasteve** [comment]
No I get that.  Sorry for my ignorance, but does that mean you're doing a completely new architecture?  Or does that mean you're using the exact same architecture as formly for ng1 but just adapting it for ng2?

**Comment by mohammedzamakhan** [comment]
@cudasteve We have new architecture completely

**Comment by egucciar** [comment]
Can you elaborate on what the major differences are between angular 1.x formly, besides angular 2 difference from angular one, what are the major architectural design difference?
