### ISSUE TITLE
Aurelia-formly

### ISSUE THREAD

**Issue by aluanhaddad** [formly-js/ng2-formly#63]
I've been an Angular 1.x developer for several years now. One of the things which makes it such a strong platform are a number of great libraries. Of these, I would put angular-formly in the top 3, right alongside ui-router and angular-bootstrap. However, we now live in a richer ecosystem with more frameworks to choose from than ever.

After having spent time using both angular 2 and Aurelia, I personally find the latter to be superior in almost every way. However, angular formly is uniquely powerful and elegantly solves a plethora of problems.

Given this I plan to create an analogous library for Aurelia using this project as a starting point. Before doing so, I wanted to get feedback from the maintainers of this repository as well as the Aurelia community.

My intent is not to start a framework war or fragment this fantastic community, but simply to bring the power of the formerly model to another framework.
I would very much appreciate thoughts on this.

**Comment by kentcdodds** [comment]
I think that'd be fantastic. Why don't you start a repo on your own user, and if it becomes a thing, we can transfer it to the formly-js org :+1:

**Comment by aluanhaddad** [comment]
@kentcdodds that was my plan. Thanks for your support and enthusiasm!

**Comment by EisenbergEffect** [comment]
@aluanhaddad We'd love to see you create a formly for Aurelia. Definitely catch up with @jdanyow who is working on our validation and can assist you with any integration guidance you may need. Keep us posted. I'm excited to see what you put together!

**Comment by aluanhaddad** [comment]
@EisenbergEffect thanks! I'll be sure to do that. It may take me a little while to get this off the ground is I'm fairly new to developing client-side libraries, having worked mainly in the application space, but I'm ready to get started and very excited.

**Comment by divyakumarjain** [comment]
Closing this issue as Formly for Aurelia should be created in new repository and issue should be tracked there.
