### ISSUE TITLE
select options not showing

### ISSUE THREAD

**Issue by mptorrejon** [formly-js/ng2-formly#67]
Hello,
I have this piece of code along with other inputs and checkboxes, but I do not know why select does not show the options within my array.

`{
				className: "col-xs-8",
				key: "dropdown",
				type: "select",
				templateOptions: {
					options: [
						{
				                  "name" : "Option-A",
				                  "value": "OptionA",

				               }
					]
				}
			}
`
If I set another set of name/value I can see my dropdown having two empty options, but no text.

Can anyone please tell me what Im doing wrong?

thanks a lot

**Comment by turlife** [comment]
@mptorrejon  Hi, did you solve your problem?

**Comment by aitboudad** [comment]
@turlife see https://github.com/formly-js/ng-formly/blob/master/demo/hello.ts#L159-L169
