### ISSUE TITLE
ng2-formly.min.js:1 Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by crouti** [formly-js/ng2-formly#68]
Importing ng2-formly.min.js from CDN 
`https://cdnjs.cloudflare.com/ajax/libs/ng2-formly/2.0.0-beta.5/ng2-formly.min.js`

loading the file in the Ionic2 index.html results in the console error mentioned in title 

`ng2-formly.min.js:1 Uncaught ReferenceError: System is not defined`

Any idea ?
Thanks

**Comment by divyakumarjain** [comment]
You need to make sure system.js is used for loading the dependencies.

**Comment by divyakumarjain** [comment]
Will close this issue. Will reopen if it is happening even if system.js is included in the application.
