### ISSUE TITLE
having multiple button in the form

### ISSUE THREAD

**Issue by mptorrejon** [formly-js/ng2-formly#69]
I know that in formly-forms for angular1 there is a
type: 'button'
which will create a button and bind a callback(function) to it.

Is there something similar in ng2-formly? I would like to add multiple buttons with different functionality in a form.

Please advise,

**Comment by stephanjust** [comment]
AFAIK formly does not allow you to do that. You could use `input `elements of type `button`, but you can not specify a callback to be triggered.

However, formly can easily be extended. If you have a look at [the demo in line 62](https://github.com/formly-js/ng2-formly/blob/master/demo/hello.ts):
```
["input", "checkbox", "radio", "select", "textarea", "multicheckbox"].forEach(function (field) {
    fc.setType({
        name: field,
        component: TemplateDirectives[field]
    });
});
```
This is were you tell formly which component to use for which type. If you want add a new type, e.g. button, you can use
```
fc.setType({
    name: 'button',
    component: YourButtonDirective
});
```
and formly will instantiate it. Just check one of the [existing templates](https://github.com/formly-js/ng2-formly/tree/master/src/templates) or use [the interface](https://github.com/formly-js/ng2-formly/blob/master/src/components/formly.field.config.ts) to ensure you access all fields correctly.

**Comment by divyakumarjain** [comment]
As mention by @stephanjust you can create new directive after referring to existing template.

Another way is to have buttons in template itself like below

`<formly-form [model]="user" [fields]="userFields" (formSubmit)="console($event)" [form]="form">
        <button type="submit" class="btn btn-primary" (click)="submit(user)">Button</button>
    </formly-form>`


this is copied from demo application's template.html using in hello.ts.
