### ISSUE TITLE
Feature requests: add styling support for field-groups and make fields optional

### ISSUE THREAD

**Issue by stephanjust** [formly-js/ng2-formly#74]
The demo is a great example on how to use the bootstrap row and col-** classes to create a proper form. However, bootstrap allows to [nest rows](http://getbootstrap.com/css/#grid-nesting) but that behavior can't get replicated by formly.

Requirements to get it to work:
1) Encapsulate ```FormlyFieldGroup``` in a div and allow to set it's class.
2) Allow to set the class in the for-loop of ```FormlyFieldGroup``` (just as in ```FormlyForm```)
3) Make the ```FormlyField``` in ```FormlyFieldGroup``` optional so that just nesting them multiple times without adding fields is possible (again, just as in ```FormlyForm```, but instead of allowing just one, the field should be optional).
4) I assume I forgot something, so feel free to add whatever else is required.

This allows to create layouts such as [this one](http://www.bootply.com/akZbzIccOG). My particular use case is a picture spanning multiple rows (with a new formly field that supports pictures) in the form.

**Comment by divyakumarjain** [comment]
@stephanjust do you have a sample where this issue is reproduced? so that we can quickly debug it.

**Comment by stephanjust** [comment]
Well, a lacking feature is kinda hart to give samples for, but I assume examples for the supposed behavior could help.

https://plnkr.co/edit/SS40AbzaRuVwNFnqc77C?p=preview
This is the desired outcome (borders only to visualize it). One row containing two columns, whereas the first column contains two rows again (potentially infinite).

As far as I can see formly simply can't output this type of HTML because you can not create nested divs with more than 2 levels. The JSON I would like to use:

```
[{
	"className": "row",
	"fieldGroup": [{
		"className": "col-xs-9",
		"fieldGroup": [{
			"className": "row",
			"fieldGroup": [{
				"className": "col-xs-12"
				// formlyfield 1
			}]
		}, {
			"className": "row",
			"fieldGroup": [{
				"className": "col-xs-12"
				// formlyfield2
			}]
		}]
	}, {
		"className": "col-xs-9"
		// formlyfield3
	}]
}]
```

While the ```className``` is used in [```FormlyForm```](https://github.com/formly-js/ng2-formly/blob/master/src/components/formly.form.ts)to wrap a ```FieldGroup```in a css class
```
<form class="formly" role="form" novalidate [formGroup]="form">
              <div class="formly-field"
                *ngFor="let f of fields"
                [ngClass]="f.className">
```
this is not the case for the [```FieldGroup```](https://github.com/formly-js/ng2-formly/blob/master/src/components/formly.field.group.ts)itself.
```
<div  class="formly-field"
          *ngFor="let f of field.fieldGroup"> // missing [ngClass] because it is used only for the next field
```
