### ISSUE TITLE
Several templates not checking for disabled attribute

### ISSUE THREAD

**Issue by stephanjust** [formly-js/ng2-formly#75]
In comparison to input, checkbox and textarea, the templates for select, multicheckbox and radio are not evaluating the disabled attribute of templateOptions and therefore can't be disabled.

**Comment by divyakumarjain** [comment]
Pull request 76 opened for fixing multicheckbox and radio button.

**Comment by divyakumarjain** [comment]
Have updated the pull request for Select control too.
