### ISSUE TITLE
Add Unit tests

### ISSUE THREAD

**Issue by divyakumarjain** [formly-js/ng2-formly#79]

**Comment by brutalcrozt** [comment]
what will we use for unit test?

**Comment by divyakumarjain** [comment]
Plan is to use Karma runner for triggering the unit test cases along with karma-jasmine plugin. Also planning to leverage @angular/testing module.

**Comment by aitboudad** [comment]
I'll try provide an initial work soon!

**Comment by mohammedzamakhan** [comment]
The karma is out of date as well

karma 0.13.22	 current 1.3.0
karma-chrome-launcher 0.2.3 current 2.0.0
karma-firefox-launcher	0.1.7 current 1.0.0
karma-jasmine 0.3.8 current 1.0.2
karma-typescript-preprocessor 0.1.3 current 0.3.0

**Comment by aitboudad** [comment]
closing in favor of  #182
