### ISSUE TITLE
Add ng2Module support

### ISSUE THREAD

**Issue by divyakumarjain** [formly-js/ng2-formly#80]
https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html

**Comment by divyakumarjain** [comment]
i started some work on this and seems to be running into issue will post these issue in forms and will check how it can be handled.

**Comment by divyakumarjain** [comment]
Work in progress branch [divyakumarjain/#80](https://github.com/divyakumarjain/ng2-formly/tree/%2380) which is compiling but giving runtime issue for FormlyPubSub Injection.

**Comment by aitboudad** [comment]
Hi @divyakumarjain, I was already doing some initial work on this, let me know if you want to finish this task or leave it for me.
Thanks :)

**Comment by divyakumarjain** [comment]
Thanks @aitboudad for the PR it look good at high level. I will have another look at it and will merge.
