### ISSUE TITLE
css class form-control missing in most templates

### ISSUE THREAD

**Issue by stephanjust** [formly-js/ng2-formly#82]
input and textearea templates both have the css class form-control included. All others don't. This causes styling to be non-uniform between different fields.

**Comment by stephanjust** [comment]
(Didn't want to open another issue for basically the same thing)

The select template is also missing the form-group css class on the surrounding div, causing basically the same issues.

**Comment by divyakumarjain** [comment]
Adding form-control to checkbox and radio button breaks the styling on bootstrap 3. Not sure if its good idea to do it.
