### ISSUE TITLE
Repository for material templates

### ISSUE THREAD

**Issue by divyakumarjain** [formly-js/ng2-formly#88]
Following is initial draft for material2 templates.

https://github.com/divyakumarjain/ng2-formly-template-material

We have following two options

1. Mono repo for all templates under ng2-formly. (The way angular2, material2 has all the modules in same repo).
2. Separate repo for each type of template implementation.

The second has an advantage that each template can have its own issue repo.

**Comment by mohammedzamakhan** [comment]
👍 2nd options makes a lot of sense.

**Comment by mohammedzamakhan** [comment]
Can you create this repo in formly-js organization instead of created it in your personal repository please

**Comment by divyakumarjain** [comment]
Sorry I did not realize that i had access to create new repo in formly-js organization. Let me know if you are ok with ng2-formly-template-material name and i will go ahead and create one.

**Comment by mohammedzamakhan** [comment]
Yes it looks perfect 👍
