### ISSUE TITLE
Can't bind to 'ngFormModel'

### ISSUE THREAD

**Issue by hendrikhh** [formly-js/ng2-formly#89]
Hi,
I try to setup ng2-formly with IonicV2.
But there is this error:
`
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'ngFormModel' since it isn't a known native property ("
            <form class="formly" role="form" novalidate [ERROR ->][ngFormModel]="form">
              <div class="formly-field"
                *ngFor="let f of fields"): FormlyForm@1:56
`

Any idea?
Thanks

**Comment by divyakumarjain** [comment]
Can you provide version of ng2-formly used and also angular version. Also Plunker will help.

**Comment by hendrikhh** [comment]
Im using angular rc4 (included in the ionic 2 tabs template)
and "ng2-formly": "^2.0.0-beta.5".
I set it up like this https://github.com/formly-js/ng2-formly/issues/66
The "No Directive annotation found on FormlyForm" error disappears and there is this new one

**Comment by divyakumarjain** [comment]
@hendrikhh let us know if you face same issue with angular rc5 and @angular/form@0.3.0 Seems like issue with version miss match.

**Comment by mohammedzamakhan** [comment]
it could be because we did not publish 2.0.0-beta.6 or any other update to npm yet?!
