### ISSUE TITLE
Invalid provider - only instances of Provider and Type are allowed, got: undefined

### ISSUE THREAD

**Issue by anupamarachuri** [formly-js/ng2-formly#90]
import {Component} from '@angular/core';
import {FormlyForm, FormlyConfig, FormlyMessages, TemplateDirectives,FormlyProviders} from 'ng2-formly'
import {bootstrap } from '@angular/platform-browser-dynamic';

@Component({
  selector: 'sd-about',
  template: `
        <h1>Hello, {{name}}!</h1>
        Say hello to: <input [value]="name" (input)="name = $event.target.value">
        <formly-form [model]="user" [fields]="userFields"></formly-form>
    `,
  directives: [FormlyForm],
  providers: [FormlyConfig, FormlyMessages]
})
export class AboutComponent {
  name: string = 'World';
  user = {};
  userFields;
  constructor(fc: FormlyConfig) {
    ['input', 'checkbox'].forEach((field) => {
      fc.setType({
        name: field,
        component: TemplateDirectives[field]
      })
    });

    this.userFields = [{
      key: 'nameOfPerson',
      type: 'input',
      templateOptions: {}
    }]
  }
}

bootstrap(AboutComponent, [FormlyProviders]);

Could you please help?

**## Error is: Invalid provider - only instances of Provider and Type are allowed, got: undefined**

**Apart from this file, it is a big project which also has a main.ts:**

import { platformBrowserDynamic,bootstrap } from '@angular/platform-browser-dynamic';

// The app module
import { AppModule } from './app.module';

// Compile and launch the module
//noinspection TypeScriptValidateTypes
platformBrowserDynamic().bootstrapModule(AppModule);

**Comment by divyakumarjain** [comment]
Can you please share the version of ng2-formly and angular version.

**Comment by anupamarachuri** [comment]
Angular Version is Angular v2.0.0-rc.5
ng2-formly@2.0.0-beta.5
