### ISSUE TITLE
Support @angular/form 2.0.0-rc.6

### ISSUE THREAD

**Issue by divyakumarjain** [formly-js/ng2-formly#92]
Upgrading to @angular/form 2.0.0-rc.6 causes following issues

- [ ] disable attribute binding is not supported (see https://github.com/angular/angular/issues/11324)
- [ ] Field with validation error cannot be added during ngOnInit (see https://github.com/angular/angular/issues/10131)

**Comment by divyakumarjain** [comment]
Work In Progress as following branch.
https://github.com/divyakumarjain/ng2-formly/tree/2.0.0-beta.6

**Comment by aitboudad** [comment]
based on your initial work, see #101
